# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_scraped', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_posted', models.DateTimeField(verbose_name='date published')),
                ('keywords', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('sponsored', models.BooleanField(default='False')),
                ('expired', models.BooleanField(default='False')),
            ],
        ),
    ]
