# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='keywords',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_scraped',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
