# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170128_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='snippet',
            field=models.TextField(default='no description available'),
        ),
    ]
