# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
